channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::numpy=1.26.3
  - conda-forge::matplotlib=3.3.2
  - conda-forge::tqdm=4.66.1
  - conda-forge::seaborn=0.13.0
  - conda-forge::ipykernel=6.29.0
  - conda-forge::tensorboard=2.15.1
  - conda-forge::conda=23.11.0
  - conda-forge::hydra-core=1.3.2
  - conda-forge::pip=23.3.2
  - conda-forge::jupyter=1.0.0
  - conda-forge::imageio=2.33.1
  - conda-forge::imageio-ffmpeg=0.4.9
  - pytorch::pytorch=2.1.2
  - pytorch::pytorch-cuda=12.1
  - pip:
      - torchrl==0.2.1
      - dm-control==1.0.16